<?php declare(strict_types=1);?>
<!--
<form xmlns="http://www.w3.org/1999/html" data-mage-init='{"validation": {}}'>
    <div class="control">
       <input type="text" name="email" id="email" class="input-text"
       placeholder="<?/*= __('Your Email') */?>"
       data-validate="{required:true, 'validate-email': true}" />
    </div>
    <button type="submit" class="action-primary"> <?/*= __('Submit') */?></button>
</form>-->



<!--<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "component-a": {
                        "component": "SimplifiedMagento_CustomAdmin/js/ui-component-a"
                    },
                    "component-b": {
                        "component": "SimplifiedMagento_CustomAdmin/js/ui-component-b"
                    }
                }
            }
        }
    }
</script>

<div data-bind="scope: 'component-a'">
    <h3 data-bind="text: label"></h3>
    <div data-bind="text: amount"></div>
</div>
<div data-bind="scope: 'component-b'">
    <h3 data-bind="text: label"></h3>
    <div data-bind="text: amount"></div>
</div>-->

<!--"active": true, "saveState": true, "animate": {"duration": 600,"easing": "linear"}-->
<!--<div id="my_collapsible" data-mage-init='{"SimplifiedMagento_CustomAdmin/js/dynamic-collapsible": {"ajaxContent": true}}'>
    <div data-role="title">
        <h2>How about a collapsible widget? <button data-role="trigger">GO</button> </h2>
    </div>
    <div id="example" data-role="content"></div>
    <a href="<?/*= $block->getViewFileUrl('SimplifiedMagento_CustomAdmin/example-content.html') */?>" data-ajax="true"></a>
</div>-->

<!--<script type="text/x-magento-init">
    {
        "#target": {
            "alaiasexample": {
                "base_url": "<?/*= $block->escapeJs($block->getBaseUrl()) */?>"
            }
        }
    }
</script>
<pre id="target"></pre>-->

<!--<div id="target" data-mage-init='{"SimplifiedMagento_CustomAdmin/js/requirejs-example": { "base_url": "/"}}'></div>-->

<div data-mage-init='{"redirectpath-v1": {}}'></div>